export const UPDATE_POSTS = "UPDATE_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const SET_CURRENT_POST = "SET_CURRENT_POST";
export const ADD_POST = "ADD_POST";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";

export const UPDATE_ITEM = "UPDATE_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const ADD_ITEM = "ADD_ITEM";

export const UPDATE_LAYOUT = "UPDATE_LAYOUT";
export const REMOVE_LAYOUT = "REMOVE_LAYOUT";
export const SET_CURRENT_LAYOUT = "SET_CURRENT_LAYOUT";
export const ADD_LAYOUT = "ADD_LAYOUT";

export const UPDATE_WAREHOUSE = "UPDATE_WAREHOUSE";
export const REMOVE_WAREHOUSE = "REMOVE_WAREHOUSE";
export const SET_CURRENT_WAREHOUSE = "SET_CURRENT_WAREHOUSE";
export const ADD_WAREHOUSE = "ADD_WAREHOUSE";

export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
export const REMOVE_INVENTORY = "REMOVE_INVENTORY";
export const SET_CURRENT_INVENTORY = "SET_CURRENT_INVENTORY";
export const ADD_INVENTORY = "ADD_INVENTORY";

export const UPDATE_BINQTY = "UPDATE_BINQTY";
export const REMOVE_BINQTY = "REMOVE_BINQTY";
export const SET_CURRENT_BINQTY = "SET_CURRENT_BINQTY";
export const ADD_BINQTY = "ADD_BINQTY";

export const DD_WAREHOUSE = "DD_WAREHOUSE";
export const DD_BIN = "DD_BIN";
export const DD_SHELF = "DD_SHELF";